// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4ll5IvOH0uTu0rgAam7knRr1KehPTrhk',
    appId: '1:965984278020:web:6bd5f0d71d13e4a53b0751',
    messagingSenderId: '965984278020',
    projectId: 'hehe2-b05f5',
    authDomain: 'hehe2-b05f5.firebaseapp.com',
    storageBucket: 'hehe2-b05f5.appspot.com',
    measurementId: 'G-RE1R1Q54P3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8WUrHlDQROA6J-aUebPmJrutisI1wRh0',
    appId: '1:965984278020:android:16c5a43ef54e35993b0751',
    messagingSenderId: '965984278020',
    projectId: 'hehe2-b05f5',
    storageBucket: 'hehe2-b05f5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBlWzlVYIKs-7H0StWq1p_CEKdcwv4Q5XU',
    appId: '1:965984278020:ios:e9a0cae70f1afb3e3b0751',
    messagingSenderId: '965984278020',
    projectId: 'hehe2-b05f5',
    storageBucket: 'hehe2-b05f5.appspot.com',
    iosBundleId: 'com.example.gtkFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBlWzlVYIKs-7H0StWq1p_CEKdcwv4Q5XU',
    appId: '1:965984278020:ios:e9a0cae70f1afb3e3b0751',
    messagingSenderId: '965984278020',
    projectId: 'hehe2-b05f5',
    storageBucket: 'hehe2-b05f5.appspot.com',
    iosBundleId: 'com.example.gtkFlutter',
  );
}
